[package]
name = "ouch"
version = "0.2.0"
authors = ["Vinícius Rodrigues Miguel <vrmiguel99@gmail.com>", "João M. Bezerra <marcospb19@hotmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/vrmiguel/ouch"
license = "MIT"
keywords = ["decompression", "compression", "zip", "tar", "gzip"]
categories = ["command-line-utilities", "compression", "encoding"]
description = "A command-line utility for easily compressing and decompressing files and directories."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty        = "0.2.14"
lazy_static = "1.4.0"
walkdir     = "2.3.2"
strsim      = "0.10.0"
bzip2       = "0.4.3"
libc        = "0.2.103"
tar         = "0.4.37"
xz2         = "0.1.6"
zip         = { version =  "0.5.13", default-features = false, features = ["deflate-miniz"] }
flate2      = { version = "1.0.22", default-features = false, features = ["zlib"] }

[target.'cfg(all(target_family = "unix", target_arch = "x86_64"))'.dependencies]
zstd        = { version = "0.9.0", default-features = false, features = ["thin"] }

[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))'.dependencies]
zstd        = { version = "0.9.0" }

[target.'cfg(all(target_family = "windows", target_arch = "x86_64"))'.dependencies]
zstd        = { version = "0.9.0" }

[target.'cfg(target_family = "x86-64")'.dependencies]

[target.'cfg(all(target_arch = "x86-64", not(target_os = "windows")))'.dependencies]

[dev-dependencies]
tempfile = "3.2.0"
rand = { version = "0.8.3", default-features = false, features = ["small_rng", "std"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
